-- Trigger for constraining the rating of reviews

DROP TRIGGER TRIG_REVIEW_RATING;

CREATE TRIGGER TRIG_REVIEW_RATING
    BEFORE INSERT ON FN45454.REVIEW
    REFERENCING NEW AS N
    FOR EACH ROW
    WHEN (N.RATING > 10 OR N.RATING < 1)
    BEGIN
        IF N.RATING > 10 THEN
            SET N.RATING = 10;
        ELSE
            SET N.RATING = 1;
        END IF;
    END;


INSERT INTO REVIEW (FROM, RATING, TEXT, SERIESID, EPISODENUMBER, EPISODESEASON)
 VALUES ('TRIGGER_TEST', 15, 'TRIGGER_TEST', FN45454.GET_SERIES_ID('Gravity Falls'), 1, 1);

INSERT INTO REVIEW (FROM, RATING, TEXT, SERIESID, EPISODENUMBER, EPISODESEASON)
VALUES ('TRIGGER_TEST2', -10, 'TRIGGER_TEST', FN45454.GET_SERIES_ID('Gravity Falls'), 1, 1);

SELECT RATING
FROM REVIEW
WHERE FROM LIKE 'TRIGGER_TEST%';
