DROP TABLE Genre;
DROP TABLE Actor;
DROP TABLE ActsIn;
DROP TABLE Review;

CREATE TABLE Genre (
    Id INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) CONSTRAINT PK_GENRE PRIMARY KEY,
    Name VARCHAR(50) NOT NULL
);

CREATE TABLE Actor (
    Id INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) CONSTRAINT PK_GENRE PRIMARY KEY,
    Name VARCHAR(200) NOT NULL,
    BirthDate DATE,
    ImageUrl VARCHAR(2048)
);

CREATE TABLE ActsIn (
    ActorId INT NOT NULL CONSTRAINT FK_ACTS_ACTOR REFERENCES Actor(Id),
    EpisodeId INT NOT NULL CONSTRAINT FK_ACTS_EPISODE REFERENCES Episode(Id),
    ActsAs VARCHAR(200),
    CONSTRAINT PK_ACTS_IN PRIMARY KEY(ActorId, EpisodeId, ActsAs)
);

CREATE TABLE Review (
    From VARCHAR(200) NOT NULL,
    Rating SMALLINT NOT NULL,
    Text VARCHAR(5000),
    EpisodeId INT NOT NULL CONSTRAINT FK_REVIEW_EPISODE REFERENCES Episode(Id),
    CONSTRAINT PK_REVIEW PRIMARY KEY(From, EpisodeId)
);