DROP FUNCTION GET_SERIES_RATING;

--Calculating series rating
CREATE FUNCTION GET_SERIES_RATING(SID INT)
    RETURNS DOUBLE
    RETURN
        SELECT SUM(E.RATING)/COUNT(E.NAME)
        FROM SERIES S JOIN EPISODE E on S.ID = E.SERIESID
        WHERE S.ID = SID;

SELECT NAME AS CNAME, FN45454.GET_SERIES_RATING(SERIES.ID)
FROM SERIES;


DROP FUNCTION GET_ACTOR_SERIES_COUNT;

-- Scalar function for getting how many series an actor has acted on
CREATE FUNCTION GET_ACTOR_SERIES_COUNT(A_ID INT)
    RETURNS INT
    RETURN
        SELECT COUNT(*)
        FROM (SELECT A.NAME
              FROM FN45454.ACTOR A
              JOIN FN45454.ACTOR_ROLE AR on A.ID = AR.ACTORID
              WHERE A.ID = A_ID
              GROUP BY A.NAME, AR.SERIESID)
        GROUP BY NAME;


SELECT NAME, FN45454.GET_ACTOR_SERIES_COUNT(ACTOR.ID)
FROM ACTOR;

DROP FUNCTION SERIES_BY_GENRE;

-- Function to return series by genre name
CREATE FUNCTION SERIES_BY_GENRE(GENRE_NAME VARCHAR(50))
RETURNS TABLE(Id INT, Name VARCHAR(150), Description VARCHAR(5000))
RETURN
    SELECT S.ID, S.NAME, S.DESCRIPTION
    FROM SERIES S
    JOIN SERIES_GENRE SG on S.ID = SG.SERIESID
    JOIN GENRE G on SG.GENREID = G.ID
    WHERE G.NAME = GENRE_NAME;

SELECT *
FROM TABLE(FN45454.SERIES_BY_GENRE('Comedy'));

