DROP VIEW GOOD_SERIES;

--Series that are considered good. Series with rating above 6
CREATE VIEW GOOD_SERIES
AS
    SELECT *
    FROM SERIES
    WHERE FN45454.GET_SERIES_RATING(ID) > 6.0;

SELECT *
FROM FN45454.GOOD_SERIES;

-- View for series that have more than 3 reviews
DROP VIEW SERIES_WITH_MANY_REVIEWS;

CREATE VIEW SERIES_WITH_MANY_REVIEWS AS
SELECT *
FROM FN45454.SERIES
WHERE ID IN (SELECT SERIESID
             FROM FN45454.REVIEW
             GROUP BY SERIESID
             HAVING COUNT(*) >= 3);

SELECT * FROM EPISODE;
SELECT * FROM SERIES_WITH_MANY_REVIEWS;
