DROP FUNCTION GET_SERIES_RATING;

--Calculating series rating
CREATE FUNCTION GET_SERIES_RATING(SID INT)
    RETURNS DOUBLE
    RETURN
        SELECT SUM(E.RATING)/COUNT(E.NAME)
        FROM SERIES S JOIN EPISODE E on S.ID = E.SERIESID
        WHERE S.ID = SID;

SELECT NAME AS CNAME, FN45454.GET_SERIES_RATING(SERIES.ID)
FROM SERIES;